### PR TITLE
[BUGFIX] Use correct module routes

### LINKED ISSUE #1271: Backend Modules not loading
## Bug Report

**Current Behavior**
When using the search form within the news administration module an Exception is thrown.
```
#1425389240 TYPO3\CMS\Backend\Routing\Exception\ResourceNotFoundException
The requested resource "/module/web/NewsAdministration" was not found.
in /var/www/html/public/typo3/sysext/backend/Classes/Routing/Router.php line 78
```

**Expected behavior/output**
The results for the search should be loaded without an exception.

**Environment**
- TYPO3 version: 9.5.16
- news version: 8.2.0
- Composer Mode: yes
- OS: Linux (drud/ddev-webserver:v1.13.0)

**Possible Solution**
The module route that gets generated by TYPO3 for the main news module is just `/web/NewsAdministration`. When manually changing the hard coded usages of the route from `/module/web/NewsAdministration` to `/web/NewsAdministration` the module loads and the search results are shown.

**Additional context**
We only recently upgraded to News 8.0.2 and were using 7.5.3 before. The version jump was done with the recent changes in TYPO3 9.5.16 (multi domain setup with news detail pages on different sites).

Here is an exerpt of the `var_dump` done in the `TYPO3\CMS\Backend\Routing\Router->match` function, showing the config for the target module:
```
["web_NewsAdministration"]=>
  object(TYPO3\CMS\Backend\Routing\Route)#1245 (2) {
    ["path":protected]=>
    string(24) "/web/NewsAdministration/"
    ["options":protected]=>
    array(4) {
      ["module"]=>
      bool(true)
      ["moduleName"]=>
      string(22) "web_NewsAdministration"
      ["access"]=>
      string(10) "user,group"
      ["target"]=>
      string(54) "TYPO3\CMS\Extbase\Core\Bootstrap::handleBackendRequest"
    }
  }
```
This lead to the idea to change hard coded routes like this one in `Resources/Private/Templates/Administration/Index.html::49`
```
<input type="hidden" name="route" value="/module/web/NewsAdministration">
```

### PR DESCRIPTION
**Pull request by jonakieling**
Hi there,

this fixes #1271
Some hard coded backend module routes had the /module prefix which does not work in TYPO3 9.5.16 and presumably any version of 9.5. At least I could not find any changes related to backend module routing.

This fixes our TYPO3 9.5.16 instance where the previous routes resulted in an exception being thrown. See #1271 for details.

I'm curious where the /modules comes from or where it would be needed. Maybe I'm just missing something obvious.

Kind regards
Jona

### CODE REVIEW

**Comment by georgringer** [comment]
@liayn wanna test that in 10.x?

**Comment by liayn** [comment]
The search worked flawlessly for us in the latest 8.x versions. Will try it again with this change applied.

**Comment by liayn** [comment]
This change breaks in v10:

The requested resource "/web/NewsAdministration" was not found.

**Comment by jonakieling** [comment]
Added a version check for getting the module path and adjusted two occurrences where the hard coded path was used.

I've checked the search form in 9.5.17 and 10.4.2. Looks good so far.

File: Classes/Backend/RecordList/RecordListConstraint.php [hunk 1]
```diff
@@ -31,6 +32,11 @@ class RecordListConstraint
     public function isInAdministrationModule(): bool
     {
         $vars = GeneralUtility::_GET('route');
+        $version = (new Typo3Version())->getMajorVersion();
+        if ($version < 10) {
+            return $vars === '/web/NewsAdministration/';
+        }
+
```
Comment (liayn) [inline Classes/Backend/RecordList/RecordListConstraint.php:39]: what about using str(r)pos() instead of a version check for this? would be much simpler here.

`return strpos('/web/NewsAdministration/', $vars) !== false;`

**Comment by liayn** [comment]
Btw: the related core change is https://review.typo3.org/c/Packages/TYPO3.CMS/+/60433

**Comment by liayn** [comment]
A different solution would also be to set the desired path manually, as outlined in the deprecation rst file.

File: Resources/Private/Templates/Administration/Index.html [hunk 2]
```diff
@@ -46,7 +46,7 @@ <h1>
 	<f:if condition="{showSearchForm}">
 		<f:form id="administrationForm" name="demand" object="{demand}" method="get" data="{autoSubmitForm:autoSubmitForm}">
 			<input type="hidden" name="formSubmitted" value="1">
-            <input type="hidden" name="route" value="/module/web/NewsAdministration">
+            <input type="hidden" name="route" value="/module/web/NewsAdministration/">
```
Comment (liayn) [inline Resources/Private/Templates/Administration/Index.html:49]: the slash is too much

Comment (jonakieling) [reply Resources/Private/Templates/Administration/Index.html:49]: Yep, just tested it with 9 LTS and 10 LTS. It is needed with 9 and breaks with 10.

Comment (jonakieling) [reply Resources/Private/Templates/Administration/Index.html:49]: Looks like the version check is unfortunately needed after all.

Comment (jonakieling) [reply Resources/Private/Templates/Administration/Index.html:49]: I'll move my fork to a different branch to avoid the commit spam and report back when everything is tested and working with both 9 and 10.

Comment (jonakieling) [reply Resources/Private/Templates/Administration/Index.html:49]: The slash is assumed by the older version in https://review.typo3.org/c/Packages/TYPO3.CMS/+/60433/5/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php#b816. I adjusted the manual module path to include the slash. After the correct TCA was loaded without cache it now works with 9 LTS and 10 LTS.

**Comment by liayn** [comment]
Looks good by reading

**Comment by jonakieling** [comment]
Hi @liayn 

Thanks for your support in this! After checking this with flushed TCA caches the most recent commits work with both TYPO3 9 LTS and 10 LTS.

**Comment by jonakieling** [comment]
Latest update fixes the action buttons for creating and editing records on the upper button bar.
