### PR TITLE
[BUGFIX] Order news list by sorting is missing

### LINKED ISSUE #1964: [BUG] Order news list by `sorting` is missing
## Bug Report
Due to the removal of switchingControllerActions it is currently not possible to order the list view by sorting field.

**Current Behavior**
The select item is missing.

**Expected behavior/output**
It should be possible to select `sorting` out of dropdown list.

**Environment**
- TYPO3 version(s): 12.x
- news version: dev-branch 11-12
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Do not check for a selected switchableControllerAction selected in Flexforms-Field. Instead we could use selected CType to differentiate between the ordering items.

### PR DESCRIPTION
**Pull request by h3nn3s**
Due to the removal of switchingControllerActions it is currently not possible to order the list view by sorting field.

resolves #1964

### CODE REVIEW

File: Classes/Hooks/ItemsProcFunc.php [hunk 1]
```diff
@@ -106,12 +106,12 @@ public function user_orderBy(array &$config): void
...
 
             // check if there is a flexform configuration
-            if (isset($flexformConfig['data']['sDEF']['lDEF']['switchableControllerActions']['vDEF'])) {
-                $selectedActionList = $flexformConfig['data']['sDEF']['lDEF']['switchableControllerActions']['vDEF'] ?? '';
-                // check for selected action
-                if (str_starts_with($selectedActionList, 'Category')) {
+            if (isset($flexformConfig['data']['sDEF']['lDEF'])) {
+                $selectedPlugin = strtolower($row['CType']) ?? '';
+                // check for selected plugin
+                if (str_contains($selectedPlugin, 'category')) {
```
Comment (georgringer) [inline Classes/Hooks/ItemsProcFunc.php:112]: we can compare with the relevant plugin keys directly, no need to use a str_contains

**Review by georgringer — CHANGES_REQUESTED** [review]
